ANDROID-10036 Tag Evolution
Telefonica/mistica-android pull request #133
Opened 2021-12-01 12:04 UTC by dagonco

### :goal_net: What's the goal?
The objective is to evolve the Tag component to the new design.

### :construction: How do we do it?
Following the UX indications, certain attributes of the view have been modified to adapt to evolution

### ☑️ Checks
- [x] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [x] Tested with dark mode.

### :test_tube: How can I test this?
- [x] 🖼️ Screenshots/Videos
- [x] Manually

![Screenshot_20211201_123135](https://user-images.githubusercontent.com/8106237/144231422-2181d57b-92cd-4a6b-8915-8e0af3237c7b.png)

2021-12-01 12:08 UTC, dagonco commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/CatalogMainActivity.kt
> -            SectionItem("Texts", R.drawable.ic_texts, Section.TEXTS),
I have sorted this alphabetically and eliminated a dupe section.

2021-12-01 12:27 UTC, yamal-alm commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/CatalogMainActivity.kt
> -            SectionItem("Texts", R.drawable.ic_texts, Section.TEXTS),
maybe Text section is now missing? (maybe not and I'm wrong :P)

2021-12-01 12:33 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/tag/README.md
> +			app:tagStyle="Active"
lowercase?

2021-12-01 12:50 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/tag/TagView.kt
> +    }
I'm wondering if capitalizing only the first letter may be a bit restrictive...
(I know this is a decision from design team, I'm just thinking aloud)

2021-12-01 12:55 UTC, dagonco commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/CatalogMainActivity.kt
> -            SectionItem("Texts", R.drawable.ic_texts, Section.TEXTS),
Yeah, you're right. My fault.

2021-12-01 12:56 UTC, yamal-alm approved these changes
very good job 👏  @dagonco

2021-12-01 12:58 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/tag/README.md
> +			app:tagStyle="Active"
Right. 🤦🏻‍♂️

2021-12-01 13:57 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/tag/TagView.kt
> +    fun setStyle(@TagStyle style: Int, icon: Drawable? = null) {
In order to support databinding with same attribute from the style, method name should be `setTagStyle` (Or define a different binding with `@BindingMethods` like [here](https://github.com/Telefonica/mistica-android/blob/master/library/src/main/java/com/telefonica/mistica/emptystate/screen/EmptyStateScreenView.kt#L23))

2021-12-01 14:04 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/card/CardView.kt
> +            setTagStyle(styledAttrs.getInt(R.styleable.TagView_tagStyle, TagView.TYPE_PROMO))
Previous `cardTagColor` attribute was comming from `CardView` styleable. Maybe we should also make `tagStyle` to come from the CardView styleable. To clearly specify configuration this component accept by just looking its own attributes, and to make it more extensible in the future, just in case we need more tags in other places of the view.

2021-12-01 14:09 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/card/CardView.kt
> +            setTagStyle(styledAttrs.getInt(R.styleable.TagView_tagStyle, TagView.TYPE_PROMO))
Instead of `R.styleable.TagView_tagStyle` you should use `R.styleable.CardView_tagStyle` no?

2021-12-01 14:12 UTC, dpastor commented on library/src/main/res/values/attrs_colors.xml
> +        <!-- Tags colors -->
Please, remember to add also these new colors definitions and values in compose themes:

https://github.com/Telefonica/mistica-android/blob/master/library-compose/src/main/java/com/telefonica/mistica/compose/theme/color/MisticaColors.kt

Here or in another ticket, but both themes definitions (xml and compose), should always match :)

2021-12-01 14:17 UTC, dpastor commented on library/src/main/res/values/colors_movistar.xml
> +    <color name="movistar_color_blue_10">#E6F5FD</color>
Remember also to add any new colors also to the different brands compose palettes -> https://github.com/Telefonica/mistica-android/blob/master/library-compose/src/main/java/com/telefonica/mistica/compose/theme/brand/MovistarBrand.kt#L194
😄

2021-12-01 14:24 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/card/CardView.kt
> +            setTagStyle(styledAttrs.getInt(R.styleable.TagView_tagStyle, TagView.TYPE_PROMO))
My bad, you're right.

2021-12-01 14:29 UTC, dpastor commented
Adding @yceballost (Designer) to the review. (When doing visual modifications we add a designer to the review so he can check the new implementations). If possible, please generate an apk and upload it to any appcenter project, then link it in the PR description, so he can install the app and see them in the demo app to verify :)

2021-12-01 14:30 UTC, gmerinojimenez approved these changes
Nice job! 👏👏

2021-12-01 14:34 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/tag/TagView.kt
> +    fun setStyle(@TagStyle style: Int, icon: Drawable? = null) {
Perfect, I was unaware of this. I keep it in mind for the next one. Thanks!

2021-12-01 14:37 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/tag/TagView.kt
> +    private fun setIcon(@TagStyle style: Int, drawable: Drawable) {
Nice. Apart from this, I have made a slight modification.

Now I keep the tag's style, so the icon can be changed without having to pass the style again to it.
Now it looks much better. Thanks for the advice.

2021-12-01 14:39 UTC, dagonco commented on library/src/main/res/values/attrs_colors.xml
> +        <!-- Tags colors -->
Thanks. I write this down, and if you don't mind I'll leave it for the next task. So I check the entire Compose part so that I don't have anything left.

2021-12-01 14:40 UTC, dagonco commented on library/src/main/res/values/colors_movistar.xml
> +    <color name="movistar_color_blue_10">#E6F5FD</color>
Got it. Thanks!

2021-12-01 14:58 UTC, dagonco commented
Sorry @yceballost. Beginner mistakes, won't happen again!
Here you have the [app link](https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-catalog/distribution_groups/public). Please, do not hesitate to tell me if you see something wrong 😇

2021-12-02 11:05 UTC, AnaMontes11 commented on library/src/main/res/values/themes_blau.xml
> +		<item name="textTagPromo">@color/blau_color_purple</item>
This color is not correct, replace it with: @color/blau_color_purple_30

2021-12-02 11:07 UTC, yceballost requested changes

2021-12-02 11:07 UTC, yceballost commented on library/src/main/res/values/colors_o2.xml
>      <color name="o2_color_orange_light">#FFD6C2</color>
remove it

2021-12-02 11:07 UTC, yceballost commented on library/src/main/res/values/colors_o2.xml
>      <color name="o2_color_coral">#FF706E</color>
remove it, doesnt exists

2021-12-02 11:07 UTC, yceballost commented on library/src/main/res/values/colors_o2.xml
>      <color name="o2_color_pink">#CB31A0</color>
new hex `#E45DBF`

2021-12-02 11:07 UTC, yceballost commented on library/src/main/res/values/colors_o2.xml
>      <color name="o2_color_pepper_dark">#D73241</color>
remove it

2021-12-02 11:07 UTC, yceballost commented on library/src/main/res/values/colors_o2.xml
>      <color name="o2_color_pepper_light30">#FFC3C8</color>
name changed to pepper20 and change hex color to `#FCC3C9`

2021-12-02 11:07 UTC, yceballost commented on library/src/main/res/values/themes_o2.xml
> +        <item name="inverse">@color/o2_color_white</item>
use colorInverse and remove this

2021-12-02 12:33 UTC, AnaMontes11 requested changes

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_o2_classic.xml
>      <color name="o2_classic_color_green_light">#DAE8B7</color>
This color is  deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_o2_classic.xml
>      <color name="o2_classic_color_pepper_light_30">#FFC3C8</color>
rename it: o2_classic_color_pepper_20

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_o2_classic.xml
>      <color name="o2_classic_color_pepper_dark">#D73241</color>
rename it: o2_classic_color_pepper_55

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_o2_classic.xml
>      <color name="o2_classic_color_orange_light">#FFD6C2</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_blue_dark">#0356C9</color>
The correct name is:  telefonica_color_blue_70

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_blue_light50">#80B2FF</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_blue_light30">#B3D1FF</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_egg_light">#F8D2B3</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_ambar_light">#F5E98A</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_ambar_dark">#AD842D</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_coral_light">#E3A19A</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_coral_dark">#912C31</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_orchid_light">#E7C2F8</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_orchid_dark">#8A1A93</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_turquoise_light">#67E0E5</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/colors_telefonica.xml
>      <color name="telefonica_color_turquoise_dark">#3E8A8A</color>
This color is deprecated, you can remove it

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/themes_o2_classic.xml
> +        <item name="inverse">@color/o2_classic_color_white</item>
use colorInverse and remove this

2021-12-02 12:33 UTC, AnaMontes11 commented on library/src/main/res/values/themes_telefonica.xml
> +        <item name="inverse">@color/telefonica_color_white</item>
use colorInverse and remove this

2021-12-02 17:38 UTC, dagonco commented
Hello, @yceballost and @AnaMontes11, as I have spoken with Yayo via chat, the nomenclature and color changes will be done in another ticket.

PS: I've removed ["inverse"](f14f8ab48cd458e8a59a6b6a67e29b96a5311397): p

2021-12-03 09:10 UTC, yceballost requested changes

2021-12-03 09:10 UTC, yceballost commented on catalog/src/main/res/layout/data_card_fragment_catalog.xml
>              android:layout_margin="8dp"
this margin have to set to 16 as a Media card, right? Both card have the same margin between Tag and Pretitle

![image](https://user-images.githubusercontent.com/6722153/144576425-6235bb9b-b4fa-40e5-bfed-0ac955ba9616.png)

2021-12-03 09:17 UTC, yceballost requested changes

2021-12-03 09:17 UTC, yceballost commented on library/src/main/res/values-night/themes_blau.xml
> +		<!-- Tag colors -->
background colors in dark mode is wrong
![image](https://user-images.githubusercontent.com/6722153/144577382-80d4a2bd-9d46-4dbe-b3b0-f6f47ee7176e.png)

it has to look like this
![image](https://user-images.githubusercontent.com/6722153/144577436-b36bf159-5c81-4e82-ab1d-f159bbc16c58.png)

2021-12-03 10:34 UTC, dagonco commented on library/src/main/res/values-night/themes_blau.xml
> +		<!-- Tag colors -->
Nice catch, the problem was not related to the color, that was fine. The blend mode used was what was not right.
![Screenshot 2021-12-03 at 11 33 30](https://user-images.githubusercontent.com/8106237/144588268-0fda2fa7-2252-4872-91a3-011ef03c951e.png)

2021-12-03 10:42 UTC, yceballost commented on library/src/main/res/values-night/themes_blau.xml
> +		<!-- Tag colors -->
nice! ✨

2021-12-03 10:57 UTC, AnaMontes11 commented
On the app I can't see the tags on the row list component @dagonco How can I review it? thanks!

2021-12-03 12:15 UTC, dagonco commented on catalog/src/main/res/layout/data_card_fragment_catalog.xml
>              android:layout_margin="8dp"
Oh, you looked in the wrong place. That view belongs to the "Data Card" section screen. And is the distance between text boxes.

The change you mean is in this [commit](https://github.com/Telefonica/mistica-android/pull/133/commits/c448837bbb8fc0336da2eb12848ce62c25b4eee3).

2021-12-03 12:22 UTC, dagonco commented
> On the app I can't see the tags on the row list component @dagonco How can I review it? thanks!

Sorry @AnaMontes11, but I've seen Tags aren't being used in that component. 
Is there something that I'm missing?

2021-12-03 12:31 UTC, AnaMontes11 commented
> > On the app I can't see the tags on the row list component @dagonco How can I review it? thanks!
> 
> Sorry @AnaMontes11, but I've seen Tags aren't being used in that component. 
> Is there something that I'm missing?![Screenshot_20211203_122836.jpg](https://user-images.githubusercontent.com/88187691/144602816-959bf050-2eda-4362-bc63-c5e2eff31efd.jpg)

I would like to check how the tags in this component work @dagonco

2021-12-07 07:45 UTC, dagonco commented
Morning, @AnaMontes11. I have modified the ListRow component so that a Tag can be added.
In order to take a look at it, you have to download the [latest version](https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-catalog/distribution_groups/public).

2021-12-07 10:06 UTC, AnaMontes11 commented
> Morning, @AnaMontes11. I have modified ListRow component so that a Tag can be added. You have to download the [latest version](https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-catalog/distribution_groups/public) to check it.
> 
> ![Screenshot 2021-12-07 at 08 46 09](https://user-images.githubusercontent.com/8106237/144987714-7948f318-c2df-4075-9db3-c41871b08617.png)

hi @dagonco I can´t install this version. There seems to be an error. I've deleted the previous version, but it still won't let me download it...

2021-12-07 12:39 UTC, dagonco commented
Give it another try, please! @AnaMontes11

2021-12-07 12:46 UTC, AnaMontes11 commented
Yes, now it works! 🚀thanks! @dagonco

2021-12-07 12:47 UTC, AnaMontes11 commented
> Give it another try, please! @AnaMontes11 

Yes, now it works! 🚀thanks! @dagonco

2021-12-09 09:00 UTC, yceballost approved these changes

2021-12-09 09:08 UTC, AnaMontes11 approved these changes

2021-12-14 15:12 UTC, merged