ANDROID-11048 Several fixes in Sheet
Telefonica/mistica-android pull request #179
Opened 2022-09-15 16:37 UTC by gmerinojimenez

### :goal_net: What's the goal?
Several fixes detected by design team

### :construction: How do we do it?

### ☑️ Checks
- [ ] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [ ] Tested with dark mode.
- [ ] Tested with API 21.

### :test_tube: How can I test this?

https://user-images.githubusercontent.com/4595241/190459532-9daf0585-bd93-4d0d-99f8-92710647f51f.mp4

2022-09-15 16:38 UTC, gmerinojimenez commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/CatalogMainActivity.kt
> +            SectionItem("Sheet", R.drawable.ic_bottomsheet, Section.BOTTOM_SHEET),
the official name is Sheet

2022-09-15 16:38 UTC, gmerinojimenez commented on library/build.gradle
> +    api "com.google.android.material:material:1.6.1"
Needed to be able to setup the max height

2022-09-15 16:40 UTC, gmerinojimenez commented on catalog/src/main/res/layout/screen_fragment_bottom_sheet_catalog.xml
> +				app:inputCheckText="Rows with description" />
new parameters to be able to test

2022-09-15 16:41 UTC, gmerinojimenez commented on library/src/main/res/layout/bottom_sheet_layout.xml
> +				android:id="@+id/container_outer"
using nested scroll to be able to coordinate the scroll

2022-09-15 18:15 UTC, yceballost requested changes
1. Handle is not using `control` as a color constant. This cause a bad color in dark mode.
2. Is overlay using backgroundOverlay as a color constant?
3. Is it possible to make the animation smoother than now?
We found some curves for animation here
https://github.com/material-components/material-components-android/search?q=cubic+bezier 

nice job🙌

2022-09-16 07:10 UTC, gmerinojimenez commented
@yceballost : https://github.com/Telefonica/mistica-android/pull/179/commits/01ee797f7e2fb0124df569cac6ecdb624d41bf0b

* Updated the handler color.
* Updated the icon in the catalog list

2022-09-16 07:15 UTC, dpastor approved these changes
Nice! 👍

2022-09-16 07:24 UTC, dagonco approved these changes
Niiice! 🚀

2022-09-16 09:02 UTC, yceballost approved these changes
nice job! ✨

2022-09-16 09:05 UTC, merged