ANDROID-11320 Add colorCustomTabsBackground to all brands
Telefonica/mistica-android pull request #190
Opened 2022-11-16 14:34 UTC by jeslat

### :goal_net: What's the goal?
Add a new color `colorCustomTabsBackground` to all brands following the changes of this PR https://github.com/Telefonica/mistica-design/pull/892.

### ☑️ Checks
- [x] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [x] Tested with dark mode.
- [x] Tested with API 21.

2022-11-16 15:46 UTC, jdelga approved these changes

2022-11-16 22:39 UTC, yceballost requested changes
Can I get an apk to test this? o maybe if you can attach some screenshot will be enough to validate the change :)

2022-11-17 10:23 UTC, dagonco approved these changes
Great! 👌🏻

2022-11-18 09:14 UTC, yceballost approved these changes
great! thanks!

2022-11-18 09:56 UTC, merged