ANDROID-11388 button compose
Telefonica/mistica-android pull request #208
Opened 2023-02-24 10:46 UTC by jdelga

### :goal_net: What's the goal?
Provide a `Button` implementation in Compose

### :construction: How do we do it?
Provide a `Button` implementation in Compose

### ☑️ Checks
- [ ] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [X] Tested with dark mode.
- [X] Tested with API 21.

### :test_tube: How can I test this?

Mistica Catalog

![image](https://user-images.githubusercontent.com/36664452/221159460-a57b519c-1c83-4bf0-866a-7f92e4f35f6e.png)
![image](https://user-images.githubusercontent.com/36664452/221159661-ace5322b-1544-41a0-822e-cc85a7a75676.png)

2023-02-24 12:14 UTC, yamal-alm requested changes
Very nice job 👏  just a few minor comments

2023-02-24 12:14 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +    val iconSpacing = 10.dp
I would move this variable out to a constant :)

2023-02-24 12:14 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +            contentPadding = PaddingValues(16.dp, 0.dp, 16.dp, 0.dp),
minor: if you want you can use `PaddingValues(horizontal = 16.dp, vertical = 0.dp)` instead

2023-02-24 12:14 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                        )
I think we should add the spacer and the text only when `loadingText` is not null or blank to avoid having the circular progress slightly moved to the left

2023-02-24 12:14 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +    var originalWidth: Dp? by remember { mutableStateOf(null) }
just curiosity: what is this for?

2023-02-24 12:14 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonStyles.kt
> +        disabledBackgroundColor = colorResource(R.color.button_primary_background_selector).disabled()
Can we use colors from `MisticaTheme.colors` instead of xml ones?

2023-02-24 12:17 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +    val iconSpacing = 10.dp
Constants declare with `const` are only allowed for primitives and strings

2023-02-24 12:24 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +    var originalWidth: Dp? by remember { mutableStateOf(null) }
This takes the final width of the button so it is used to keep the size when the `loadingText` is applied. Without this, the width of the button would change on recomposition

2023-02-24 12:29 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +    val iconSpacing = 10.dp
we can declare the constant as an int and add `.dp` part later, but no worries, it is just a small optimization

2023-02-27 14:56 UTC, dpastor commented
Could you check if we can replace current implementation with a `ComposeView` that feeds from composable?

I'm adding @gmerinojimenez to the review also. He has tested it in the past and may have relevant feedback also.

2023-02-27 15:24 UTC, jdelga commented
I think it still makes sense to keep the xml implementation due to all usages that it has currently across projects

2023-02-27 15:49 UTC, jdelga commented
I think for now we can keep the xml implementation and keep working in the new Composable components, due to all usages that the xml button has.

Maybe some day as part of other task we can review its implementation and see if it worths removing the "leaking" `MaterialButton` interface, which would mean a mayor version including breaking changes.

2023-02-27 15:58 UTC, yceballost requested changes
i need a build of compose version to review this pr

2023-02-28 08:44 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> -    ButtonStyle.SECONDARY -> R.layout.button_secondary_wrapper
all these layouts can be deleted, no?

2023-02-28 08:59 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +        androidx.compose.material.Button(
are we applying corner radius of 4.dp somewhere? as specs mention?

2023-02-28 09:00 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    minHeight = 48.dp,
this is the "height", not the "minHeight", right?

2023-02-28 09:02 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
>  fun Button(
Specs mention additional buttons tipologies, like IconButton and TextLink --> https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=238%3A6756&t=XA0vdHDzO9DdQY3n-0

I think we should also give support for them through specific composable function.

2023-02-28 09:04 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
Animation has an specific pattern defined in specs --> https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A1039&t=XA0vdHDzO9DdQY3n-0

We should configure it accordingly

2023-02-28 09:08 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 0.dp),
Component specs define specific vertical padding of 12.dp also --> https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A655&t=XA0vdHDzO9DdQY3n-0

is the button already applying that?

2023-02-28 09:31 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    textStyle = MisticaTheme.typography.preset3Medium,
should we use medium presets, or regular?

Specs mention regular weights -> https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A719&t=XA0vdHDzO9DdQY3n-0

2023-02-28 09:36 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
I don't understand what animation do you mean. Video links are not working

2023-02-28 09:37 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    textStyle = MisticaTheme.typography.preset3Medium,
XML button was updated to this specs ? Do I need to check it too ?

2023-02-28 09:37 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                        Text(
Is the ellipsis behaviour applied by default?

https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=238%3A6303&t=XA0vdHDzO9DdQY3n-0

2023-02-28 09:45 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
There you can see animation behaviour specified, xml component `ProgressButton` has that animation curve already implemented, you can check it on the component itself.
Please, ask design to fix links on spec also.

2023-02-28 09:49 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    textStyle = MisticaTheme.typography.preset3Medium,
If there are discrepancies in specs vs what is implemented, we need to find what is the correct thing. And update whatever is wrong :)

2023-02-28 09:49 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
I don't see any difference between the ProgressButton and the new Compose button, if you can explain a bit better, please.

2023-02-28 10:58 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
>  fun Button(
`ButtonStyle.LINK` is already implemented, I will check Icon Button 👌

2023-02-28 11:00 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +        androidx.compose.material.Button(
You can check the default shape:
![image](https://user-images.githubusercontent.com/36664452/221834746-5725da85-8cb3-4dec-9d70-886f244ae193.png)

2023-02-28 11:33 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
>  fun Button(
`TextLink` is not the same as a button with link style. `TextLink` is an underscored clickable text.

2023-02-28 11:35 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
What i mean --> Is compose button by default using same opacity and bezier curve defined in the specs?

<img width="706" alt="Captura de pantalla 2023-02-28 a las 12 34 22" src="https://user-images.githubusercontent.com/5360064/221842308-019c4d3c-1674-4e2a-8f5e-723fc92c7e06.png">

2023-02-28 15:52 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    textStyle = MisticaTheme.typography.preset3Medium,
Docs show `preset3Medium` and `preset2Medium` for small

https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A1039&t=15OzfbUIgHqcvfYm-0

2023-02-28 15:53 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    minHeight = 48.dp,
Renamed

2023-03-01 09:51 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/ButtonSizes.kt
> +    textStyle = MisticaTheme.typography.preset3Medium,
Ok, when clicking on button details shows medium, right.
I just saw text styles page, which does not explicitly mention "medium" weight (and regular is the default) -->

<img width="495" alt="Captura de pantalla 2023-03-01 a las 10 47 15" src="https://user-images.githubusercontent.com/5360064/222104049-4827840f-9e44-41b1-8092-0dd8317b862a.png">

It looks medium is and was the correct weight.

2023-03-01 10:42 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
done

2023-03-01 10:43 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 0.dp),
done

2023-03-01 10:43 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                        Text(
done

2023-03-01 14:56 UTC, yceballost requested changes

2023-03-01 14:56 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> -    ButtonStyle.SECONDARY_INVERSE -> R.layout.button_secondary_inverse_wrapper
we changed hover of buttonSecondary months ago, would be nice to have the last definition here <3

![image](https://user-images.githubusercontent.com/6722153/222176128-eb7b4a7f-9f6e-4389-85a5-bb649971284a.png)

https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A256&t=xucSY1ydSOKnBETg-4

2023-03-01 14:56 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
Can you remove uppercase from mística catalog buttons examples? Buttons always have to use sentence case

2023-03-02 10:24 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
>  fun Button(
Ok!

2023-03-02 10:39 UTC, dpastor commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> +                    exit = slideOutVertically { it },
Nicely done ;)

2023-03-06 08:36 UTC, yamal-alm approved these changes

2023-03-09 15:13 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/compose/button/Button.kt
> -    ButtonStyle.SECONDARY_INVERSE -> R.layout.button_secondary_inverse_wrapper
Done! Thanks!

2023-03-09 17:13 UTC, yceballost approved these changes
really nice 😍

2023-03-10 09:09 UTC, merged