ANDROID-11501 load error feedback compose
Telefonica/mistica-android pull request #225
Opened 2023-04-03 15:40 UTC by jdelga

### :goal_net: What's the goal?
Add Load Error Feedback Compose implementation

### :construction: How do we do it?
Add the new component
Add helpers into catalog

### ☑️ Checks
- [X] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [X] Tested with dark mode.
- [X] Tested with API 21.

### :test_tube: How can I test this?

![image](https://user-images.githubusercontent.com/36664452/229559339-3d9fccfe-75f7-4c75-b76c-130eaaecb5f6.png)
![image](https://user-images.githubusercontent.com/36664452/229559413-2950ba02-59b8-4491-8342-9dd676cca619.png)

2023-04-03 16:09 UTC, yamal-alm requested changes
Looks good 👏  just a few comments

2023-04-03 16:09 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/feedback/error/LoadErrorFeedback.kt
> +    loadingAction: () -> Unit,
I would use something like `onClick` or `onButtonClick`

2023-04-03 16:09 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/feedback/error/LoadErrorFeedback.kt
> +                    .align(Alignment.CenterHorizontally),
this can be moved to the parent `Column` just one time instead of on every child:
```
Column(
   ...
   horizontalAlignment = Alignment.CenterHorizontally
)
```

2023-04-03 16:09 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/compose/feedback/error/README.md
> +) {
I would add here the name of the `loadingAction` param to make it more explicit. I think using it as a trailing lambda may lead to confusion and make the developer think that it accepts other composables WDYT

2023-04-04 06:24 UTC, dagonco commented on catalog-compose/src/main/java/com/telefonica/mistica/compose/catalog/ui/components/LoadErrorFeedbacks.kt
> +            modifier = Modifier.padding(horizontal = 50.dp),
That's a minor, probably this field width will be increased if text is long enough.
Maybe something like Modifier.fillwidth().padding(yourHorizontalPadding) could avoid that.

2023-04-04 06:26 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/compose/feedback/error/LoadErrorFeedback.kt
> +package com.telefonica.mistica.compose.feedback
Check package.
```suggestion
package com.telefonica.mistica.compose.feedback.error
```

2023-04-04 06:34 UTC, dagonco approved these changes
That's cool!

2023-04-04 08:09 UTC, jdelga commented
Applied comments

2023-04-04 08:13 UTC, yamal-alm approved these changes
👏

2023-04-10 12:59 UTC, yceballost commented
This component never was defined by Mística Design team, is just a legacy from Tuenti. So.. should we include this component in Mística?

This component can be replaced by Feedback Error Screen

2023-04-10 13:07 UTC, jdelga commented
I think we should add the compose version of this component to keep working on the new compose components. However, we can consider a new component to substitute this one or remove it.

2023-04-11 09:42 UTC, merged