Android 11507 migrate high lighted card compose
Telefonica/mistica-android pull request #242
Opened 2023-05-08 09:08 UTC by afernandezalabarce

[Task](https://jira.tid.es/browse/ANDROID-11507)

### :goal_net: What's the goal?
Repair some bugs and integrate HighLightedCard into mistica catalog

### :construction: How do we do it?
Repair some bugs and integrate with Mistica catalog
Compose catalog for mistica are developed with reactive ui changes.

### ☑️ Checks
- [X] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [X] Tested with dark mode.
- [X] Tested with API 23.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [ ] 🖼️ Screenshots/Videos
- [ ] Mistica App QR or download link
- [ ] Reviewed by Mistica design team
- [ ] ...

2023-05-08 09:10 UTC, afernandezalabarce commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +package com.telefonica.mistica.catalog.ui.compose.components
this file is the reactive ui for compose with the goal of check ui of HighLightedCard composable

2023-05-08 09:11 UTC, afernandezalabarce commented on library/src/main/java/com/telefonica/mistica/compose/card/highlightedcard/HighLightedCard.kt
> +            modifier = modifier.drawBehind {
to paint background, due lacks on paint with old format, are best to paint with drawbehind.

2023-05-10 07:21 UTC, gmerinojimenez commented
Compose:
![image](https://github.com/Telefonica/mistica-android/assets/4595241/c392c2eb-744e-4747-87ce-57637f080dd9)
XML:
![image](https://github.com/Telefonica/mistica-android/assets/4595241/a9517e23-0794-43bf-9511-ad70d35f3cc5)

The colors doesn't match between implementations, can you check it? :)

2023-05-10 07:23 UTC, gmerinojimenez commented
There should be a margin between the text and the image:
XML:
![image](https://github.com/Telefonica/mistica-android/assets/4595241/57fb48bf-7940-4a05-a87f-9ebc2b595691)
Compose:
![image](https://github.com/Telefonica/mistica-android/assets/4595241/c4184b62-0f3a-48ce-a817-6b176ca03d7a)

2023-05-10 08:16 UTC, afernandezalabarce commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +            OutlinedTextField(
Done!

2023-05-10 08:38 UTC, haynlo approved these changes
Good job

2023-05-10 10:14 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
In the classic tab of the highlighted card when you press any card button (close, primary button, ...) it shows a Toast indicating that it has been pressed. Maybe you should add this behaviour in compose tab too

2023-05-10 10:50 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +                RadioButton(selected = buttonConfig.buttonStyle == ButtonStyle.PRIMARY, onClick = { onButtonTypeSelected(buttonConfig.copy(buttonStyle = ButtonStyle.PRIMARY)) })
Line too long

2023-05-10 10:50 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +                RadioButton(selected = buttonConfig.buttonStyle == ButtonStyle.SECONDARY, onClick = { onButtonTypeSelected(buttonConfig.copy(buttonStyle = ButtonStyle.SECONDARY)) })
Line too long

2023-05-10 10:51 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +                RadioButton(selected = buttonConfig.buttonStyle == ButtonStyle.LINK, onClick = { onButtonTypeSelected(buttonConfig.copy(buttonStyle = ButtonStyle.LINK)) })
Line too long

2023-05-10 11:16 UTC, pmartinbTEF commented
Different bottom margin for the fit image.
Classic:
![Captura de pantalla de 2023-05-10 13-14-26](https://github.com/Telefonica/mistica-android/assets/49242917/a43e4538-bbbd-4d2c-a29b-e8f8524eddc6)
Compose:
![Captura de pantalla de 2023-05-10 13-14-38](https://github.com/Telefonica/mistica-android/assets/49242917/a320af40-cc08-457a-9624-e043b53c7e39)

2023-05-10 11:16 UTC, pmartinbTEF requested changes
Good job! please check comments

2023-05-10 11:55 UTC, afernandezalabarce commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +                RadioButton(selected = buttonConfig.buttonStyle == ButtonStyle.SECONDARY, onClick = { onButtonTypeSelected(buttonConfig.copy(buttonStyle = ButtonStyle.SECONDARY)) })
done!

2023-05-10 11:55 UTC, afernandezalabarce commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/HighLightedCards.kt
> +                RadioButton(selected = buttonConfig.buttonStyle == ButtonStyle.LINK, onClick = { onButtonTypeSelected(buttonConfig.copy(buttonStyle = ButtonStyle.LINK)) })
done!

2023-05-12 08:52 UTC, pmartinbTEF approved these changes
Great!

2023-05-16 09:59 UTC, gmerinojimenez approved these changes
Good job! thank you!

2023-05-17 09:50 UTC, merged