Migrate pop over to compose ANDROID-11502
Telefonica/mistica-android pull request #246
Opened 2023-05-19 09:44 UTC by fjquileze

🎟️ Jira tickets

[Task](https://jira.tid.es/browse/ANDROID-11502)

### :goal_net: What's the goal?
Migrate XML PopOver implementation to Compose

### :construction: How do we do it?
Added new PopOver composable

### ☑️ Checks
- [ ] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [ ] Tested with dark mode.
- [ ] Tested with API 23.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [ ] 🖼️ Screenshots/Videos
- [ ] Mistica App QR or download link
- [ ] Reviewed by Mistica design team
- [ ] ...

2023-05-22 10:51 UTC, DevPabloGarcia commented
Testing the app I found some problems. 
* When the title text is too long, it shows under the "X" close button and description is not shown.
* When the title fit the popover but the description is too long, the pop over doesn't expand.

Checking the xml behavior, title and description could be fit in multiple lines.
![Screenshot_20230522_124612](https://github.com/Telefonica/mistica-android/assets/42326032/e73d83d9-c14d-47c6-814e-907360f1a4ea)
![Screenshot_20230522_124840](https://github.com/Telefonica/mistica-android/assets/42326032/94aeb8aa-8723-43de-9418-aabd4b0afc61)

2023-05-22 10:52 UTC, DevPabloGarcia requested changes
I found some errors, please check it 😄

2023-05-22 15:17 UTC, gmerinojimenez commented
Hi, minor, but the arrow is not starting from the component, looks like there is an extra space, no?

![telegram-cloud-photo-size-4-6005900280828377764-x](https://github.com/Telefonica/mistica-android/assets/4595241/77ac6974-32d7-487a-a9a7-971831dd9676)

2023-05-22 15:19 UTC, gmerinojimenez commented on library/src/main/java/com/telefonica/mistica/compose/popover/PopOver.kt
> +                        )
I think this should be limited to only one line

2023-05-22 15:26 UTC, gmerinojimenez commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/PopOvers.kt
> +    var selectedItemIndex by remember { mutableStateOf<Int?>(0) }
maybe we can keep an enum to improve the readability :)
```kotlin
enum PopoverPosition {
    Auto, Top, Bottom
}
```

2023-05-22 15:29 UTC, gmerinojimenez requested changes
Nice job! please check the small required changes and you have it :)

2023-05-23 16:51 UTC, fjquileze commented
> 
fixed! 👍

2023-05-23 16:52 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/popover/PopOver.kt
> +                )
fixed! 👍

2023-05-23 16:52 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/popover/PopOver.kt
> +                        )
I checked the figma documentation about the pop overs and has to be limited to 2, I'm gonna change it

2023-05-23 16:54 UTC, fjquileze commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/PopOvers.kt
> +    var selectedItemIndex by remember { mutableStateOf<Int?>(0) }
Good point, I'm going to change it

2023-05-25 06:32 UTC, gmerinojimenez approved these changes
Good job!

2023-05-29 15:30 UTC, DevPabloGarcia approved these changes
Awesome!

2023-06-21 08:22 UTC, aweell approved these changes

2023-06-21 08:24 UTC, merged