ANDROID-13240 compose custom icon
Telefonica/mistica-android pull request #248
Opened 2023-05-24 15:54 UTC by jdelga

### :goal_net: What's the goal?
The main goal is to add the new `CUSTOM` type to the compose implementation which was already added to the XML implementation: https://github.com/Telefonica/mistica-android/pull/243

Afterwards, I have checked there are some improvements that could be done to the catalog itself to avoid the duplication of the inputs.

### :boom: What's the goal?
* Breaking change: `TYPE_CUSTOM` must be changed to `TYPE_INFO`
* `shouldAnimateOnAttachedToWindow` change to `setShouldAnimateOnAttachedToWindow(boolean)` or by xml

### :construction: How do we do it?
* Add CUSTOM implementation in Compose
* Add `shouldAnimateOnAttached` option in the xml itself (poyake)
* Add CUSTOM icons and animations to the input options. Instead of updating the two different input layouts, I have merged them into a single one with two different launch options.

### ☑️ Checks
- [X] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [X] Tested with dark mode.
- [X] Tested with API 23.

### :test_tube: How can I test this?

Before:

https://github.com/Telefonica/mistica-android/assets/36664452/7bf2339b-70d2-4792-bcc4-7111e22a5b1e

After:

https://github.com/Telefonica/mistica-android/assets/36664452/b3b78f1e-1007-4604-a608-bff5dfc7e363

2023-05-25 12:24 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/ComponentCatalogActivity.kt
> +    private fun setSingleInputLauncher(
New method for components that have only one input and are launched with the different implementations

2023-05-25 12:26 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/CommonButtonLaunchBlock.kt
> +fun CommmonButtonLaunchBlock(
Common launch block, to be reused

2023-05-29 08:13 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
> +            if (!shouldAnimateOnAttached){
shouldn't it be?
if (shouldAnimateOnAttached){

2023-05-29 08:26 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +    }
could be moved to else block of line 119?

2023-05-29 08:28 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +        ConstraintLayout {
If this is common code for compose/classic it should be outside an else block no?

2023-05-29 09:12 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +    }
I don't see you point, the flag `showFeedbackClassic` launches a new activity, while `showFeedbackCompose` draws over the same view.

2023-05-29 09:14 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +        ConstraintLayout {
It is common, however, it is drawn in the same view as the Feedback itself, so we want to draw only one of them. When the compose feedback is shown, the inputs are hidden and they are shown when we press back and `showFeedbackCompose` is false again

2023-05-29 09:57 UTC, pmartinbTEF commented on library/src/main/java/com/telefonica/mistica/feedback/screen/README.md
> +	<attr name="shouldAnimateOnAttached" format="boolean" />
Fields information entry should be added for shouldAnimateOnAttached

2023-05-29 09:59 UTC, pmartinbTEF requested changes
Great job! just added a few questions

2023-05-29 10:28 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
> +            if (!shouldAnimateOnAttached){
Keep in mind that this is the catalog, not the library, so if we have enabled `shouldAnimateOnAttached` then we don't need to perform the animation manually.

We only need it if we disable `shouldAnimateOnAttached`

2023-05-29 10:58 UTC, pmartinbTEF commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +        ConstraintLayout {
I would add a third var showCatalogInputs or something similar to avoid using showFeedbackCompose for two different things

2023-05-29 11:00 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +        ConstraintLayout {
but "show catalog inputs" is the case when the two others is false.

2023-05-29 11:27 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/feedback/screen/README.md
> +	<attr name="shouldAnimateOnAttached" format="boolean" />
Done

2023-05-29 15:24 UTC, DevPabloGarcia reviewed
Nice approach! Check little comments

2023-05-29 15:24 UTC, DevPabloGarcia commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/CommonButtonLaunchBlock.kt
> +        Spacer(modifier = Modifier.height(20.dp))
Question: Instead of using different spacers, we can set Row composable: modifier.padding(20.dp) ?

2023-05-29 15:24 UTC, DevPabloGarcia commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +        ConstraintLayout {
I would extract this code for a new file like: FeedbacksForm.kt

2023-05-29 15:28 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/CommonButtonLaunchBlock.kt
> +        Spacer(modifier = Modifier.height(20.dp))
No problem, I don't see any difference between them

2023-05-29 15:29 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Feedbacks.kt
> +        ConstraintLayout {
The feedback is going to be different for each component, I don't think it's reusable. However, I can move it to a different composable for cleanness, WDYT?

2023-05-29 15:32 UTC, pmartinbTEF approved these changes
Good job!

2023-05-29 16:10 UTC, yceballost requested changes

2023-05-29 16:10 UTC, yceballost commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
To avoid bad usage in mistica catalog, can you change the custom icon to this
https://github.com/Telefonica/mistica-icons/blob/production/icons/telefonica/light/lifeguard-float-light.svg

an example
![image](https://github.com/Telefonica/mistica-android/assets/6722153/2e7e016e-f759-4896-962a-c1fa22a5727a)

2023-05-29 16:10 UTC, yceballost commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
Its a bit weird to mix feedback typologies (Success, error, info) with custom typology. In my mind was better to change between typologies and inside the informative type, you can change to a custom icon.

Custom icon is just for INFO Screen

2023-05-30 10:41 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
There are no mixed typologies, we have added a new one called "Custom" that allows a custom icon or animation. However, the icon defaults to the INFO one if it is not set.

In the other hand, previous type INFO does not have any changes.

2023-05-30 10:52 UTC, yceballost commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
This approach is far from how it is approached from the design side. When a designer uses this in Figma, he will use the `InfoFeedbackScreen` and change the icon of this component, not use a `CustomFeedbackScreen`, fyi.

I think it's important that the design and development approach should be aligned so that when I get designs to the development teams, things appear coherent when the screens are analyzed.

for example
![image](https://github.com/Telefonica/mistica-android/assets/6722153/dabc9c5b-9de9-4025-8e62-a46deaff07e5)

2023-05-30 11:02 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
I understood that with "custom" there were no limitations on the icon chosen. Is this fixed to some specific icons ?

2023-05-30 11:03 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
![Captura de pantalla 2023-05-30 a las 13 02 46](https://github.com/Telefonica/mistica-android/assets/36664452/e2e38669-736f-40a7-b65a-d3d103c655e7)

2023-05-30 11:05 UTC, jdelga commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/activity/FeedbackScreenCatalogActivity.kt
Ok then, thanks

2023-05-30 15:18 UTC, DevPabloGarcia approved these changes

2023-06-01 10:23 UTC, jeslat approved these changes

2023-06-01 10:48 UTC, yceballost approved these changes

2023-06-01 10:54 UTC, merged