ANDROID-10902 Skeletons (Compose)
Telefonica/mistica-android pull request #263
Opened 2023-06-14 08:45 UTC by gmerinojimenez

### :goal_net: What's the goal?
Provide an implementation for skeletons (only in compose right now)
### :construction: How do we do it?
Just a box with different shapes and an animation

### ☑️ Checks
- [X] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [X] Tested with dark mode.
- [ ] Tested with API 23.

### :test_tube: How can I test this?
![skeletonsLight](https://github.com/Telefonica/mistica-android/assets/4595241/31a2641a-5af2-4be4-9d72-1b7dac4e3a1a)
![skeletonsDark](https://github.com/Telefonica/mistica-android/assets/4595241/c8b94dc4-06ca-424f-a88b-b2bfc9a99340)

2023-06-14 09:10 UTC, dagonco approved these changes
Terrific! 💀

2023-07-05 12:04 UTC, yceballost requested changes

2023-07-07 10:23 UTC, gmerinojimenez commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/ComponentCatalogActivity.kt
Added, I will generate a new catalog app soon :)

2023-07-07 12:51 UTC, yceballost approved these changes
Nice!

2023-07-10 06:26 UTC, merged