Feature/android 13547 sheet with action buttons
Telefonica/mistica-android pull request #293
Opened 2023-08-14 14:10 UTC by jeprubio

### :tickets: Jira ticket
[ANDROID-13547](https://jira.tid.es/browse/ANDROID-13547)

### :goal_net: What's the goal?
Creating the Sheet Component Bottom Actions.

### :construction: How do we do it?
- Links with chevron is needed: https://github.com/Telefonica/mistica-android/pull/292
- Adding the new ComponentType: BottomActions
- Creating the new layout sheet_bottom_actions.xml just for the buttons.
- BottomActions.toView to display the new view with the buttons.
- Adding access to set the text and Chevron from the code in MisticaButton.
- Added withBottomActions() to be used by the bridge.

### ☑️ Checks
- [x] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [x] Tested with dark mode.
- [ ] Tested with API 23.

### :test_tube: How can I test this?
It can be accessed in the Sheet section by selecting Children Type: BottomActions.
- [x] 🖼️ Screenshots/Videos
![BottomActions](https://github.com/Telefonica/mistica-android/assets/13270085/956d82e1-6b7a-4ed7-95cf-2c7a23662bff)
https://github.com/Telefonica/mistica-android/assets/13270085/002c68b2-1f97-4f61-900f-5a1298c2902b
- [x] Mistica App QR or download link
- [x] Reviewed by Mistica design team

2023-08-16 14:37 UTC, jeprubio commented on build.gradle
> +        androidx_appcompat_version = "1.6.0"
This is unrelated to the task, I saw it could be updated and did it. No problem in reverting this if asked to.

2023-08-16 14:38 UTC, jeprubio commented on library/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
This lib is needed for the fix of the BottomSheetDialog in order to support compose in it.

2023-08-16 15:32 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/button2/Button.kt
> +    var text: String by mutableStateOf("")
But in the case of the chevron you have kept it private and added a setter method `showChevron()`

I would do the same here.

2023-08-16 15:35 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +                secondaryButton?.text = this.secondaryButton?.title.orEmpty()
`this.linkButton` is already checked and it is available as non null as `button`

2023-08-16 15:36 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +                secondaryButton?.text = this.secondaryButton?.title.orEmpty()
`this.linkButton` is already checked and it is available as non null as `button`


```suggestion
                secondaryButton?.text = button.title
```

2023-08-16 15:37 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +                linkButton?.text = this.linkButton?.title.orEmpty()
Same:

```suggestion
                linkButton?.text = button.title
```

2023-08-16 15:39 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +                secondaryButton?.text = this.secondaryButton?.title.orEmpty()
Yup, that makes sense, updated.
Thanks!

2023-08-16 15:40 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +                linkButton?.text = this.linkButton?.title.orEmpty()
Updated. Thanks

2023-08-17 13:17 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/button2/Button.kt
> +    var text: String by mutableStateOf("")
My suggestion was precisely having them private and use a setter

2023-08-21 11:03 UTC, yceballost requested changes

2023-08-21 11:03 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
Everything works fine! 

But the style of some elements still needs to be changed, as we added in the jira ticket:
We also took the opportunity to include a small restyling in this component (for better visualization you can see these updates marked in red in the specifications within anatomy and text) but they are the following:
-Title -> text-preset-5
-Subtitle -> text-preset-3
-Draggable area height -> 32px
-The padding between the text content and the interactive content becomes 8px.
-Action height in Action list type -> 72px

2023-08-21 11:04 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
If I change this it will be changed for the other Sheet types that are not action buttons, is that ok?

2023-08-21 11:11 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
These visual changes apply for all sheets :)

2023-08-21 11:25 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +        while (currentContext != null) {
Not sure if a loop is the best approach, just I'm afraid of infinite loops.
Could we have something more loop-proof and also, why is the reason to have this? Why actual view context is not enough?

2023-08-21 11:29 UTC, dagonco commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +    return LayoutInflater.from(context).inflate(R.layout.sheet_bottom_actions, container, false)
IMHO, is kinda difficult to read this method. But It's just my point of view, not necessary to change if y'all fine.

2023-08-21 12:03 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +        while (currentContext != null) {
It can't be infinite cause it's getting every time the baseContext, so at some point that must be null:
```
while (currentContext != null) {
    if (currentContext is Activity) return currentContext
    if (currentContext !is ContextWrapper) break
    currentContext = currentContext.baseContext
}
return null
```
It also only continues while that current context is not an Activity and is a ContextWrapper.
The code is from: https://stackoverflow.com/questions/72395779/using-a-composeview-inside-layout-or-a-bottomsheetdialog-throws-exception and it's because the BottomSheetDialog we have in the project is not implementing lifecycle so it crashes when using compose into it unless that lifecycle is implemented, which this is doing.

2023-08-21 12:10 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
> +    return LayoutInflater.from(context).inflate(R.layout.sheet_bottom_actions, container, false)
The signature follows the same way the other types of sheet follow, see: ListSingleSelection.toView, ListActions.toView, ListInformative.toView
I've extracted the code of the setBottomActionElements if that seems better [e847ee1](https://github.com/Telefonica/mistica-android/pull/293/commits/e847ee1c30102cfef55e9afa63307712bddd53fa)

2023-08-21 12:17 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/button2/Button.kt
> +    var text: String by mutableStateOf("")
Yup, in the Sheet.kt after the values are set I've tried adding:
```
GlobalScope.launch {
  while(true) {
      delay(1_000)
      linkButton?.withChevron = true
      delay(1_000)
      linkButton?.withChevron = false
  }
}
```
(sorry for the code, it's just for demonstration) and the chevron is updating all the time with the new values.

2023-08-21 12:59 UTC, nimeacuerdo commented
@jdelga @yceballost anything else from your side that blocks this PR?

2023-08-21 13:36 UTC, jdelga approved these changes

2023-08-22 21:39 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
I can't see the last changes in the last update in Mística Catalog, can you check if the last version include this changes?

2023-08-23 07:03 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/sheet/Sheet.kt
Checked. It does, indeed. The title is preset 5, the subtitle is preset 3 and the paddings are changed:

![title_preset5](https://github.com/Telefonica/mistica-android/assets/13270085/2fafd9dd-3f33-4d1e-bdab-a5acdfc928f0)

![subtitle_preset3](https://github.com/Telefonica/mistica-android/assets/13270085/f5d91316-a259-4d61-95a6-c6b7450ddf85)

2023-08-23 07:38 UTC, merged