New Snackbar spec
Telefonica/mistica-android pull request #306
Opened 2023-10-17 10:24 UTC by yamal-alm

### :goal_net: What's the goal?
_Provide a description of the overall goal. The description in the Jira ticket may help._

### :construction: How do we do it?
_Provide a description of the implementation. A list of steps would be ideal._
* _Step 1_
* _Step 2_
* _Step 3_

### ☑️ Checks
- [ ] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [ ] Tested with dark mode.
- [ ] Tested with API 23.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [ ] 🖼️ Screenshots/Videos
- [ ] Mistica App QR or download link
- [ ] Reviewed by Mistica design team
- [ ] ...

2023-10-19 09:16 UTC, yamal-alm commented on library/src/main/res/layout/snackbar_custom_layout_merge.xml
> +<merge xmlns:android="http://schemas.android.com/apk/res/android"
file almost indentical to the original layout from Material library implementation

2023-10-19 09:19 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +        snackbar.showDismissActionIfNeeded(hasInfiniteDuration = snackbarLength == SnackbarLength.INDEFINITE)
all these customizations are managed inside `CustomSnackbarLayout` class

2023-10-19 09:20 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +        }
if the snackbar has an indefinite duration, the user should be able to manually dismiss it. In case the action opens some screen or trigger some event that the user doesn't want to execute, then we should provide an alternative way to dismiss the snackbar by showing the dismiss button

2023-10-19 10:39 UTC, jdelga reviewed
Good job! I have added some questions.

2023-10-19 10:39 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +    open fun showCritical(snackbarLength: SnackbarLength? = null): Snackbar {
Why is the default changed ?

2023-10-19 10:39 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +            snackbarLength == null -> if (actionListener == null) SnackbarLength.SHORT else SnackbarLength.LONG
I don't understand the relation between the length and if the listener exists or not. IMHO it should default to the previous one which was `SHORT`

2023-10-19 10:42 UTC, jdelga commented
What is the logic to change the snackbar color ?

2023-10-19 11:45 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +            snackbarLength == null -> if (actionListener == null) SnackbarLength.SHORT else SnackbarLength.LONG
Previous implementation:
- There were only two possible snackbar lengths: "short" and "long".
- Even if "short" was set on purpose by the user or by default, if any action was provided, then the duration would be set to "long". This is like that by definition. 

New implementation:
- One more length choice: "indefinite".
- If no duration is explicitly selected, we use the same approach as before: if no action is set, then we use "short", if an action is provided then "long" is used instead.


However, I think `if (actionListener == null)` should be replaced with `if (actionText == null)`

2023-10-19 11:47 UTC, yamal-alm commented
> What is the logic to change the snackbar color ?

There is no logic, just the way the Snackbar is shown. We have two methods: `showCritical[ and `showInformative`

2023-10-19 13:11 UTC, jdelga commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +            snackbarLength == null -> if (actionListener == null) SnackbarLength.SHORT else SnackbarLength.LONG
Then it is more accurate now, thank you very much!

2023-10-19 13:11 UTC, jdelga approved these changes
Good job!

2023-10-19 15:46 UTC, pmartinbTEF approved these changes
Great job!

2023-10-20 11:42 UTC, idenjoe commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +            else -> snackbarLength
This code allows two cases that I think were not specified in the [specs](https://www.figma.com/file/yCHLIfy4WMfRdlADwyL4kZ/🔸-Snackbar-Specs?type=design&node-id=0-1&mode=design&t=TkcXVGbNbzi3HV08-0): 
1. Create a Snackbar without an action but with an indefinite length.
2. Create a Snackbar with an action and five seconds length.

@yceballost Should we allow these cases?

2023-10-20 11:47 UTC, idenjoe commented on library/src/main/res/layout/snackbar_custom_layout_merge.xml
> +				android:contentDescription="@string/close_button_content_description"
@yceballost @aweell According to the [specs](https://www.figma.com/file/yCHLIfy4WMfRdlADwyL4kZ/🔸-Snackbar-Specs?type=design&node-id=1038-1306&mode=design&t=jAAklkukvhlFC4lh-0) in this PR we should not include the close button which is for future development. Can you clarify it?

2023-10-20 14:13 UTC, aweell commented on library/src/main/res/layout/snackbar_custom_layout_merge.xml
> +				android:contentDescription="@string/close_button_content_description"
The dismiss action was out of the scope of this task initially. https://github.com/Telefonica/mistica-design/issues/1476

Since the snackbar action didn't perform any custom actions apart from dismiss, the user was able to dismiss the snackbar even changing the duration to infinite.

https://github.com/Telefonica/mistica-design/issues/1461 was intended as a future development. 

Since we were proposing that a custom action can be performed apart from the dismiss action. We need to ensure the user can close the snackbar, that's why the addition of the close icon.

If we're okey to merge both definitions in iOS and Web (@atabel) and follow what android already implemented I'll change the specs to include both in the same task.

I apologize for the misunderstanding @idenjoe

2023-10-23 13:29 UTC, yamal-alm commented on library/src/main/java/com/telefonica/mistica/feedback/SnackbarBuilder.kt
> +            else -> snackbarLength
Spec has been updated with a more clear description, I'll update this code according to it:
- No action: 5 seconds or indefinite with a dismiss x
- Action: 10 seconds or indefinite. Optional dimiss X

2023-10-26 14:23 UTC, idenjoe approved these changes

2023-10-27 10:16 UTC, yceballost requested changes

2023-10-27 10:16 UTC, yceballost commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/SnackBarCatalogFragment.kt
>                  val duration = when {
I think you can replace "5 seconds" & "10 seconds" radio button by "Default" in catalog 🤔

- Default
- Indefinite lenght

2023-10-27 11:59 UTC, yamal-alm commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/SnackBarCatalogFragment.kt
>                  val duration = when {
it makes sense. Then I would replace the whole radio group with just a checkbox: ☑️  Indefinite length. WDYT

2023-10-27 12:07 UTC, yceballost commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/SnackBarCatalogFragment.kt
>                  val duration = when {
perfect!

2023-10-27 12:07 UTC, yceballost approved these changes

2023-10-27 12:27 UTC, merged