ANDROID-13941 Implement Callout Image/Avatar
Telefonica/mistica-android pull request #317
Opened 2023-11-10 17:45 UTC by fjquileze

### :goal_net: What's the goal?
We need to add the image/avatar to callout element as it's specified here: [Callout Component Specs](https://www.figma.com/file/LzhzNPzE8nY9d7Yvo10d5d/%F0%9F%94%B8-Callout-Component-Specs?type=design&node-id=0%3A1&mode=design&t=ueO2qILYR1FyJOUW-1)

Currently we only have icons

### :construction: How do we do it?
* Add an image and avatar (circular image) to CalloutView
* Add the imageRes and imageConfig params to the Callout composable maintaining the old iconRes for retrocompatibility purposes

### ☑️ Checks
- [ ] I updated the documentation, including readmes and wikis. If this is a breaking change, update [UPGRADING.md](../UPGRADING.md) to inform users how to proceed. If no updates are necessary, indicate so.
- [ ] Tested with dark mode.
- [ ] Tested with API 23.

### :test_tube: How can I test this?
- [ ] 🖼️ Screenshots/Video

https://github.com/Telefonica/mistica-android/assets/129192161/19077464-9f21-429d-b7bb-93add857056d

- [ ] Mistica App QR or download link
- [ ] Reviewed by Mistica design team

2023-11-15 08:05 UTC, DevPabloGarcia reviewed
Thanks! check comments please

2023-11-15 08:05 UTC, DevPabloGarcia commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
>      @DrawableRes iconRes: Int? = null,
IMHO instead of having one attribute to icon an other to imageRes we can simplify it, and just have iconRes

2023-11-15 08:05 UTC, DevPabloGarcia commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +            if (iconRes != null) {
I don't understand this logic, first we check if iconRes is not null to create an Image, but bellow if imageConfig is IMAGE_CONFIG_ICON we create the same object?

I think we can check first the imageConfig and then create the image:


`when (imageConfig) {
    CalloutView.IMAGE_CONFIG_ICON -> // create icon
    CalloutView.IMAGE_CONFIG_SQUARE -> // create square image
    CalloutView.IMAGE_CONFIG_CIRCULAR -> //create circular image

}
`

2023-11-15 09:59 UTC, fjquileze commented on library/src/main/res/layout/callout_view.xml
> +				tools:visibility="gone"
nice catch! I'm going to remove it

2023-11-15 10:01 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +        const val IMAGE_CONFIG_NONE = -1
I was just following the code that was here before but I can make an enum

2023-11-15 10:37 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
>      @DrawableRes iconRes: Int? = null,
you're right, I'm gonna change it!

2023-11-15 10:39 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +            if (iconRes != null) {
changed!

2023-11-16 08:32 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +    ),
It would be the same that you have done in the Compose version

2023-11-16 08:33 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +                            iconRes = iconRes, iconType = IconType.SQUARE_IMAGE,
Move the `iconType` to the next line

2023-11-16 08:34 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +                    else -> noIcon()
I would not use the `else`, if in the future you add a new type, the compiler won't tell you anything.

2023-11-16 08:36 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +            if (iconRes != null) {
I would extract the icon logic to a new private composable:
´´´
if (iconRes != null) {
                Icon(imageConfig, iconRes)
            }
´´´

2023-11-20 15:44 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +    ),
Good point, I'm going to change it

2023-11-20 18:34 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +                            iconRes = iconRes, iconType = IconType.SQUARE_IMAGE,
done!

2023-11-20 18:34 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +                    else -> noIcon()
good point! changed

2023-11-20 18:37 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/compose/callout/Callout.kt
> +            if (iconRes != null) {
done!

2023-11-21 09:14 UTC, jeslat commented on library/src/main/res/values/attrs_components.xml
> -        <attr name="calloutIcon" format="reference"/>
As this is a breaking change, remember to deploy a major release and add a new section in the migrations document https://github.com/Telefonica/mistica-android/blob/main/UPGRADING.md

2023-11-21 09:14 UTC, jeslat commented on library/src/main/res/values/attrs_components.xml
> -        <attr name="calloutIcon" format="reference"/>
Change also the callout readme to add these attributes https://github.com/Telefonica/mistica-android/tree/main/library/src/main/java/com/telefonica/mistica/callout

2023-11-21 09:14 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
>          attribute = "calloutIcon",
These attributes have to have the same name as defined in `attrs_components`

2023-11-21 09:14 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +                    circularImage.visibility = GONE
I would move these visibility changes inside `setIcon` method. The same with `setImage` and `setCircularImage`

2023-11-21 09:14 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +                circularImage.visibility = VISIBLE
I think you are doing these visibility changes two times, I would remove this method

2023-11-21 10:06 UTC, DevPabloGarcia commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Callouts.kt
> +private enum class ImageTypes(val iconType: CalloutViewImageConfig) {
I found we have 3 enums for the same reason: Image Type, I think we can simplify it only using CalloutViewImageConfig.

To show the name in callout catalog we can make a function or extension function to obtain the name

2023-11-21 10:06 UTC, DevPabloGarcia commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/CalloutsCatalogFragment.kt
> +    private enum class CalloutImageConfig(val imageConfig: CalloutViewImageConfig) {
Se next comment, we are declaring 3 enums to store the same value

2023-11-21 10:06 UTC, DevPabloGarcia commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +        asset = assetRes
```suggestion
        when (assetType) {
                null,
                CalloutViewImageConfig.IMAGE_CONFIG_NONE -> noAsset()
                CalloutViewImageConfig.IMAGE_CONFIG_ICON -> setIcon(assetRes)
                CalloutViewImageConfig.IMAGE_CONFIG_SQUARE -> setImage(assetRes)
                CalloutViewImageConfig.IMAGE_CONFIG_CIRCULAR -> setCircularImage(assetRes)
            }
```

2023-11-21 11:17 UTC, yceballost requested changes

2023-11-21 11:17 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
![image](https://github.com/Telefonica/mistica-android/assets/6722153/278a91a4-3b7e-4380-a72a-e3cebb6e38c0)
this left padding is not correct when the image is "none"

An example in web
https://tinyurl.com/ykhg3dk8

2023-11-21 12:05 UTC, yceballost requested changes

2023-11-24 14:05 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
>          attribute = "calloutIcon",
done!

2023-11-24 14:19 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +                    circularImage.visibility = GONE
done 👍

2023-11-24 14:20 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +                circularImage.visibility = VISIBLE
fixed!

2023-11-24 14:21 UTC, fjquileze commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Callouts.kt
> +private enum class ImageTypes(val iconType: CalloutViewImageConfig) {
I agree, I'm gonna refactor it

2023-11-24 14:28 UTC, fjquileze commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/CalloutsCatalogFragment.kt
> +            setAssetType(imageConfig)
done!

2023-11-24 14:28 UTC, fjquileze commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/classic/components/CalloutsCatalogFragment.kt
> +    private enum class CalloutImageConfig(val imageConfig: CalloutViewImageConfig) {
fixed!

2023-11-24 14:32 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +        asset = assetRes
I don't get this change, can you explain it a little more?

2023-11-24 14:59 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
fixed!

2023-11-27 11:53 UTC, fjquileze commented on library/src/main/res/values/attrs_components.xml
> -        <attr name="calloutIcon" format="reference"/>
done!

2023-11-28 11:06 UTC, fjquileze commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
fixed! 👍

2023-11-28 14:08 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +    private fun setImageConfig(imageConfig: CalloutViewImageConfig) {
You are not using this method

2023-11-28 16:03 UTC, jeslat commented on library/src/main/java/com/telefonica/mistica/callout/CalloutView.kt
> +    private fun setImageConfig(imageConfig: CalloutViewImageConfig) {
No, you are not, you are using `setButtonsConfig`. This method is private, it's impossible that you are using it out of this class

2023-11-28 16:04 UTC, jeslat commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Callouts.kt
> +                    },
You don't need the `when`, both types are the same

2023-11-28 16:07 UTC, fjquileze commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/compose/components/Callouts.kt
> +                    },
🤦‍♂️ fixed!

2023-11-29 08:03 UTC, jeslat approved these changes
👍

2023-11-29 10:53 UTC, DevPabloGarcia approved these changes
Nice !

2023-12-01 08:58 UTC, nimeacuerdo commented
Hi @yceballost! anything left on your side to approve this?

2023-12-01 10:26 UTC, merged