ANDROID-15405 - PosterCard component
Telefonica/mistica-android pull request #398
Opened 2024-11-21 22:05 UTC by dhonti-axpe

### :goal_net: What's the goal?
First approach about **PosterCard** component creation according to current [Card Spec section](https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/%F0%9F%94%B8-Cards-Specs?node-id=2085-6958&t=mWY5kMIuusbUUWHF-4) and Figma definition.

### :construction: How do we do it?
* First of all, a `PosterCard.kt` file exposes the main component throught is provided corresponding implmementation.
* This component is divided in 3 sections:
    * TopSection
    * MainSection
    * CustomSection
* Corresponding section in catalog

### ☑️ Checks
- [ ] I updated the documentation, including readmes and wikis. If this is a breaking change, tag the PR with "Breaking Change" label and remember to include breaking change migration guide in release notes where this version is released.
- [ ] Tested with dark mode.
- [ ] Tested with API 24.
- [ ] Sync done with iOS team for this feature to ensure alignment, if applies.
- [ ] Accessibility considerations.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [ ] 🖼️ Screenshots/Videos
- [ ] Mistica App QR or download link
- [ ] Reviewed by Mistica design team
- [ ] ...

2024-11-25 15:31 UTC, haynlo reviewed
I left you some comments, but most of them are just very minor suggestions and others are doubts between you implementation and the figma's definition.

The latter is the most important thing to clarify, thanks!

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +            backgroundColor = Color.Red,
Why this red color?

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +            shape = RoundedCornerShape(16.dp),
According to Figma spec, should be "container" value instead of fixed 16.dp right?
https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/%F0%9F%94%B8-Cards-Specs?node-id=2085-7952&t=7A6BCRoDU8omYQoY-4
```suggestion
            shape = RoundedCornerShape(MisticaTheme.radius.containerBorderRadius),
```

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +            border = BorderStroke(width = 1.dp, color = MisticaTheme.colors.border),
I'm not sure if the card should have border stroke (In Figma's definition it seems that it doesn't have it). Can you confirm that please?
https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/%F0%9F%94%B8-Cards-Specs?node-id=2157-7504&t=7A6BCRoDU8omYQoY-4

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +                .let { modifierValue ->
Minor: if you want to add conditioned configuration you can better use `then()` method like:
``` kotlin
Modifier.then(onClickAction?.let {
        Modifier.clickable { it.invoke() }
    } ?: Modifier)
    
```

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            Spacer(modifier = Modifier.width(16.dp))
Mmm.. with this logic there's a case where user can define a secondTopAction without a firstTopAction. In that case, we are showing the secondTopAction as a the first one but with this  unnecessary Space.

Maybe we should adjust this logic in order to admit only second action if there's a first one, or at least show a warning log. Wdyt?

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +                .let { modifierValue ->
Same as mentioned before, you can use `then` instead

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +                .testTag(topActionData.testTag.orEmpty())
Since you are using `with` scope function you can use:
```suggestion
                .testTag(testTag.orEmpty())
```

2024-11-25 15:31 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +    data class Image(val imageResource: Int, val contentDescription: String = "") : PosterCardBackgroundType(inverseDisplay = true)
```suggestion
    data class Image(val imageResource: Int, val contentDescription: String? = null) : PosterCardBackgroundType(inverseDisplay = true)
```
Same definition as you have done here: https://github.com/Telefonica/mistica-android/pull/398/files#diff-dd2b9dff03ae4ec8918409185caf888d1146bb8ba1b837173e163a58d6f319b7R76 :)

2024-11-25 17:40 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +            border = BorderStroke(width = 1.dp, color = MisticaTheme.colors.border),
At first, like is a Card type, I assumed that will take a border in the visual representation. However checking the spec there is not any value corresponding to current border. Fixed in next!

2024-11-26 06:33 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +                .let { modifierValue ->
Instead of use that, I think that is possible to use better something like:
```
.clickable(enabled = onClick != null) {
    onClick?.invoke()
}
```

WDYT?
(Applied in this commit) --> https://github.com/Telefonica/mistica-android/pull/398/commits/91ca8546f3096629afe6e6c50d3c82ae7a6b7377

2024-11-26 06:34 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +                .let { modifierValue ->
Same response like here --> https://github.com/Telefonica/mistica-android/pull/398#discussion_r1857878790

2024-11-26 06:42 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +                .testTag(topActionData.testTag.orEmpty())
Applied here --> https://github.com/Telefonica/mistica-android/pull/398/commits/91ca8546f3096629afe6e6c50d3c82ae7a6b7377

2024-11-26 06:45 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +            border = BorderStroke(width = 1.dp, color = MisticaTheme.colors.border),
So, in order to confirm, Who would I have to ask that, @haynlo ?

2024-11-26 09:00 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            Spacer(modifier = Modifier.width(16.dp))
I provided in this commit --> https://github.com/Telefonica/mistica-android/pull/398/commits/3586a3619766976126a880f192d1e7a0d9889750
A new approach receiving a `TopActionData` list. In case list are null or the number of elements are upper than 2, list won't be displayed. I need to update the corresponding README.md file with this constraint.

WDYT?

2024-11-26 21:04 UTC, yceballost requested changes

2024-11-27 07:31 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardMainContent.kt
> +                1.0f to Color.Black.copy(alpha = 0.7f)
Thanks! Fixed in this commit --> https://github.com/Telefonica/mistica-android/pull/398/commits/faf034f9b6957d29d7f73a0168d2e01dc649c81f

2024-11-27 09:18 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +            border = BorderStroke(width = 1.dp, color = MisticaTheme.colors.border),
You can ask in the Mistica public Teams channel, por example: https://teams.microsoft.com/l/channel/19%3A68854aea147e4787803aff0e380e1208%40thread.tacv2/Help?groupId=e265fe99-929f-45d1-8154-699649674a40&tenantId=9744600e-3e04-492e-baa1-25ec245c6f10

2024-11-27 09:19 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +                .let { modifierValue ->
I didn't know the `enabled` param, looks good!

2024-11-27 09:42 UTC, haynlo commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            Spacer(modifier = Modifier.width(16.dp))
Allowing the user to add a list of n items is not entirely correct, since if they add 3 or more items, none of them will be displayed.

I still prefer the previous approach, but we can use a Pair instead to make code more readable:
``` kotlin
internal fun PosterCardTopActions(modifier: Modifier = Modifier, topActionsList: Pair<TopActionData?, TopActionData?>) {
    Row( /* ... */ ) {
        topActions.first?.let {
            // ...
        }

        if (topActions.showSpaceBetween()) Spacer(modifier = Modifer.with(16.dp))

        topActions.second?.let {
            // ...
        }
    }
}

private fun Pair<String?, String?>.showSpaceBetween() = first != null && second != null   
```

If you din't want to use Pair values, you can use specific params like in your original approach but I think it's better to provide specific params instead of a generic list, Wdyt?

2024-11-27 09:45 UTC, haynlo reviewed
I don't see any accessibility implementation.. should it be implemented here o will be implemented in a future task? https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/%F0%9F%94%B8-Cards-Specs?node-id=8552-8979&t=XBKHFm6OGwcgaRQj-4

2024-11-27 10:32 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardPreviews.kt
> +                )
Included in this commit --> https://github.com/Telefonica/mistica-android/pull/398/commits/ef9ca70dbd89b026ba3901740da2e7e1ebde242e
Change the background with a initial opacity. When user press the button a clickable effect is shown natively in Android.

2024-11-27 10:34 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
Previously due to the topActions does not receive any `onClick` event in Catalog does not show any clickable action. Now by default, a empty clickable actions is provided to sample that interaction. Also in this commit --> https://github.com/Telefonica/mistica-android/commit/ef9ca70dbd89b026ba3901740da2e7e1ebde242e

2024-11-27 10:57 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            Spacer(modifier = Modifier.width(16.dp))
Personally I prefer recovering previous implementation  (defining a `firstTopAction` and a `secondTopAction` as independent params), since if you provide a `Pair` type param, you need to provide both (`first` and `second`) params always, regardless you don't want to provide one of them as NULL value.

2024-11-27 11:30 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
I changed to previous version in this commit separating `firstAction` and `secondAction` as individual params --> https://github.com/Telefonica/mistica-android/pull/398/commits/f1f1d21c7e7760b07d35c19df2b70df84537f464

2024-11-27 11:32 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            Spacer(modifier = Modifier.width(16.dp))
I changed to previous version in this commit (https://github.com/Telefonica/mistica-android/pull/398/commits/f1f1d21c7e7760b07d35c19df2b70df84537f464) separating `firstAction` and `secondAction` as individual params.

2024-11-28 09:21 UTC, dpastor commented on library/src/main/res/drawable-nodpi/sample_background.jpg
This file is inside the library source code, can we put it in the catalog? (This increases the library size in 29.3kb, which is not needed here, right?)

2024-11-28 09:22 UTC, dpastor approved these changes
👍

2024-11-28 11:20 UTC, haynlo reviewed
Waiting for a11y implementation for final review.

2024-11-28 19:41 UTC, yceballost commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
I can't see the 48x48 tap area haha, but I will trust you! 
![image](https://github.com/user-attachments/assets/40600ac3-7e0e-4589-95ee-46c93b8eda3c)

2024-11-28 19:42 UTC, yceballost approved these changes
nice job Ɛ>

2024-12-02 15:43 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            modifier = Modifier
I think this should be modifier = modifier and not in the then at the end. If you want to add some external paddings, alignment to a box... to the TopAction it won't allow you this way it's done in here if I'm not wrong.

2024-12-02 15:48 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            TopAction(topActionData = it, modifier = Modifier.semantics { traversalIndex = 7f })
Does traversalIndex work without defining a traversalGroup? My experience was that it doesn't work, idk.

2024-12-02 15:50 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardBackground.kt
> +        modifier = Modifier
Here also I think the parameter should be the first modifier to apply and not the last one.

2024-12-02 15:51 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            modifier = Modifier
I forgot remove that reference to semantics in this composable. Change in next commit

2024-12-02 15:52 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            TopAction(topActionData = it, modifier = Modifier.semantics { traversalIndex = 7f })
I forgot remove that reference to semantics in this composable. Change in next commit

2024-12-02 15:53 UTC, dhonti-axpe commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            modifier = Modifier
You're so right!

2024-12-02 15:53 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCard.kt
> +    modifier: Modifier = Modifier,
https://blog.simprasuite.com/jetpack-compose-respect-the-contract-of-modifiers-ecbbe8ce03db#:~:text=The%20modifier%20should%20be%20the,other%20parameters%20with%20default%20values.
> The modifier should be the first optional parameter in the parameter list; after all required parameters (except for trailing lambda parameters like card content) but before any other parameters with default values.

2024-12-02 16:08 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardBackground.kt
> +        modifier = Modifier
I didn't ask for removal of the modifier parameter, just applying it well following the best practices defined in the compose api guidelines:
https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#elements-accept-and-respect-a-modifier-parameter

> Element functions MUST accept a parameter of type Modifier. This parameter MUST be named “modifier” and MUST appear as the first optional parameter in the element function's parameter list. Element functions MUST NOT accept multiple Modifier parameters.

2024-12-02 16:09 UTC, jeprubio commented on library/src/main/java/com/telefonica/mistica/compose/card/postercard/PosterCardTopActions.kt
> +            modifier = Modifier
I didn't ask for removal of the modifier parameter, just applying it well following the best practices defined in the compose api guidelines:
https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#elements-accept-and-respect-a-modifier-parameter

> Element functions MUST accept a parameter of type Modifier. This parameter MUST be named “modifier” and MUST appear as the first optional parameter in the element function's parameter list. Element functions MUST NOT accept multiple Modifier parameters.

2024-12-03 11:45 UTC, jeprubio approved these changes
👍

2024-12-03 15:02 UTC, merged