ANDROID-9466 telefonica skin
Telefonica/mistica-android pull request #85
Opened 2021-06-11 10:58 UTC by manolovn

### :goal_net: What's the goal?
Add Telefonica skin

### ☑️ Checks
- [ ] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [ ] Tested with dark mode.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [ ] 🖼️ Screenshots/Videos
- [ ] Reviewed by Mistica design team
- [ ] ...

2021-06-11 11:13 UTC, gmerinojimenez commented on .idea/codeStyles/Project.xml
>  <component name="ProjectCodeStyleConfiguration">
watchout! :)

2021-06-11 11:14 UTC, gmerinojimenez commented on library/src/main/res/values/themes_movistar.xml
> +    <style name="MisticaTheme.Telefonica.Prominent">
intended?

2021-06-11 11:14 UTC, manolovn commented on .idea/codeStyles/Project.xml
>  <component name="ProjectCodeStyleConfiguration">
F

2021-06-11 11:15 UTC, gmerinojimenez approved these changes
![](https://ak.uecdn.es/p/108/sp/10800/thumbnail/entry_id/0_yic3qis4/version/100003/width/412/height/267)

2021-06-11 11:17 UTC, manolovn commented on library/src/main/res/values/themes_movistar.xml
> +    <style name="MisticaTheme.Telefonica.Prominent">
verifying with design team

2021-06-11 11:18 UTC, manolovn commented on .idea/codeStyles/Project.xml
>  <component name="ProjectCodeStyleConfiguration">
reverted

2021-06-11 11:55 UTC, JorgeMucientes commented on library/src/main/res/values/themes_telefonica.xml
> +        <item name="feedbackScreenInfoIcon">@drawable/feedback_info_movistar</item>
hmm, should we duplicate this assets? do they share the same colors between telefonica and Moves?

2021-06-14 16:07 UTC, manolovn commented on library/src/main/res/values/themes_telefonica.xml
> +        <item name="feedbackScreenInfoIcon">@drawable/feedback_info_movistar</item>
the colors in that resources are as attributes, so there's no problem.
anyway, to ensure semantic trazability I've duplicated the resources with telefonica specific naming.
nice catch!

2021-06-15 10:43 UTC, JorgeMucientes approved these changes

2021-06-17 06:54 UTC, JorgeMucientes approved these changes

2021-06-17 06:56 UTC, JorgeMucientes approved these changes

2021-06-18 09:41 UTC, gmerinojimenez commented on catalog/src/main/java/com/telefonica/mistica/catalog/ui/fragment/HeadersCatalogFragment.kt
> +    private fun setSampleBottomLayout(checked: Boolean) {
this change is related with telefonica skin?

2021-06-18 09:42 UTC, gmerinojimenez approved these changes

2021-06-23 07:47 UTC, yceballost requested changes
I saw some wrong colors applications in dark mode, in cards for example is not applying correctly backgroundContainer

can you check if backgroundContainer = "$darkModeGrey" in dark mode?

Controls also has a wrong color in dark mode
checkbox "tick" has to be in white, and switch is not applying correct colors in dark mode

Stepper, progress specifically has a weird color when you click on "next" and the progress is filled, I think is applying MovistarBlue instead of TelefonicaBlue (I think is a problem with the rest of the brands too)

By other side, I detected a wrong color application in tabs in dark mode for Movistar, O2, Vivo, Classic O2, bottom "divider" in tabs is disappeared

You can check color application using mistica storybook to know the correct application (for control and the rest of components)
https://mistica-web.vercel.app/?path=/story/components-forms-switch--default

2021-06-23 16:07 UTC, yceballost approved these changes

2021-06-23 16:10 UTC, merged