ANDROID-9393 New empty state screen and card components
Telefonica/mistica-android pull request #91
Opened 2021-07-02 12:32 UTC by dpastor

### :goal_net: What's the goal?

Implement Screen and Card empty state components in Mistica

Ticket: [ANDROID-9393](https://jira.tid.es/browse/ANDROID-9393)
Zeplin: [Empty States](https://zpl.io/b6Kdnoq)

### :construction: How do we do it?
* Implement screen and card components as independent custom views, with databinding support
* Create two new catalog entries for each component, following same conventions used for existing components.

### ☑️ Checks
- [x] Tested with dark mode.
- [ ] Update documentation (PENDING review from design)

### :test_tube: How can I test this?
- [ ] 🖼️ Screenshots/Videos

<img src="https://user-images.githubusercontent.com/5360064/124274012-0b11b880-db41-11eb-8e88-26d9f33a5606.png" width="300"> <img src="https://user-images.githubusercontent.com/5360064/124274130-2d0b3b00-db41-11eb-816d-fc70c966da41.png" width="300">
<img src="https://user-images.githubusercontent.com/5360064/124274200-4318fb80-db41-11eb-9643-c6578037c162.png" width="300"> <img src="https://user-images.githubusercontent.com/5360064/124274243-4e6c2700-db41-11eb-8586-630bb03dfdec.png" width="300">

- [ ] Reviewed by Mistica design team
- [ ] [Hockey](https://install.appcenter.ms/orgs/tuenti-organization/apps/mistica-design-review/distribution_groups/public)

![descarga](https://user-images.githubusercontent.com/5360064/124274933-29c47f00-db42-11eb-92d7-83ea9ffce19f.png)

2021-07-02 13:07 UTC, yceballost requested changes
I can't find it in code haha but, is description using textSecondary? because I think is applying textPrimary for description and this is wrong. (in empty state screen and empty state card)

The rest is perfect!

Extraball: was really nice to have an icon instead of image asset in Icon state on the example ^.^

2021-07-05 06:24 UTC, mbarrben commented on library/src/main/res/layout/empty_state_card_view.xml
> +	<LinearLayout
This `FrameLayout` has only one child, the `LinearLayout` right below. Is it possible to make the custom view a ´LinearLayout´ instead so we simplify the hierarchy a bit? Something like:

```xml
<merge xmlns:android="http://schemas.android.com/apk/res/android"
		xmlns:tools="http://schemas.android.com/tools"
		tools:parentTag="LinearLayout"
                android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:background="@drawable/empty_state_card_view_background"
		android:focusable="true"
		android:orientation="vertical"
		android:paddingTop="24dp"
		android:paddingBottom="24dp"
		>
    ...
```

2021-07-05 06:30 UTC, mbarrben commented on library/src/main/res/layout/empty_state_card_view.xml
> +				android:layout_marginStart="0dp"
It's always weird to have asymmetry in the margins/paddings. In this case I guess it's because buttons inside may have different start margin. WDYT of configuring the start margin adding an extra 8dp to the link like:
```xml
<LinearLayout
    android:layout_marginEnd="16dp"
    android:layout_marginStart="16dp">

    <Button android:id="primary" />
    <Button android:id="secondary" />
    <Button
        android:id="link"
        android:layout_marginStart="8dp
    />
</LinearLayouta
```

2021-07-05 06:31 UTC, mbarrben commented on library/src/main/res/layout/empty_state_screen_view.xml
> +		tools:parentTag="androidx.constraintlayout.widget.ConstraintLayout"
Can't this be just a vertical LinearLayout?

2021-07-05 07:53 UTC, dpastor commented on library/src/main/res/layout/empty_state_card_view.xml
> +	<LinearLayout
Sure, it can be done. I just used the FrameLayout in order to not duplicate LinearLayout configuration both programatically and in the layout, but you are right that at the end, hierarchy simplification weights more than this. Will upload change in a new commit :)

2021-07-05 07:55 UTC, dpastor commented on library/src/main/res/layout/empty_state_screen_view.xml
> +		tools:parentTag="androidx.constraintlayout.widget.ConstraintLayout"
Yes, like in card view, I used it because it does not require to configure orientation both programatically and in the layout, but it makes sense. Will change it in a new commit :)

2021-07-05 07:59 UTC, dpastor commented on library/src/main/res/layout/empty_state_card_view.xml
> +				android:layout_marginStart="0dp"
This is the problematic scenario:

<img src="https://user-images.githubusercontent.com/5360064/124437355-45649b00-dd77-11eb-84d4-ff5c4b11fce3.png" width="300">

Link should be placed at 8dp, but from the card start, and 24dp when it is placed after any other button, while other buttons are always at 16dp.

2021-07-05 08:00 UTC, dpastor commented
> I can't find it in code haha but, is description using textSecondary? because I think is applying textPrimary for description and this is wrong. (in empty state screen and empty state card)
> 
> The rest is perfect!
> 
> Extraball: was really nice to have an icon instead of image asset in Icon state on the example ^.^

Totally correct @yceballost. I just missed that. I will upload it on a new commit. Thanks a lot.

2021-07-05 10:24 UTC, mbarrben commented on library/src/main/res/layout/empty_state_card_view.xml
> +	<LinearLayout
AFAIK you don't need to duplicate the layout configuration in Kotlin code, the merge tag does that for you.

2021-07-05 10:26 UTC, mbarrben commented on library/src/main/res/layout/empty_state_card_view.xml
> +				android:layout_marginStart="0dp"
Oh! Understood! They key part is "and 24dp when it is placed after any other button". Thanks for the explanation!

2021-07-05 10:37 UTC, mbarrben approved these changes
good job!

2021-07-05 15:31 UTC, manolovn commented
nice job man!

2021-07-05 15:31 UTC, manolovn approved these changes

2021-07-05 15:55 UTC, dpastor commented on library/src/main/res/layout/empty_state_card_view.xml
> +	<LinearLayout
As talked by chat, attributes in merge tag are not applied to the custom view. In any case i will duplicate configuration using `tools` ns just to see the layout file correctly.

2021-07-06 14:14 UTC, dpastor commented on library/src/main/res/layout/empty_state_card_view.xml
> +	<LinearLayout
https://github.com/Telefonica/mistica-android/pull/91/commits/88ef11634ccd7f4ae8dcc244f4465f9f4ecc86b7

2021-07-06 14:14 UTC, dpastor commented on library/src/main/res/layout/empty_state_screen_view.xml
> +		tools:parentTag="androidx.constraintlayout.widget.ConstraintLayout"
Fixed in https://github.com/Telefonica/mistica-android/pull/91/commits/88ef11634ccd7f4ae8dcc244f4465f9f4ecc86b7

2021-07-07 10:04 UTC, yceballost approved these changes
good job!!

2021-07-07 11:19 UTC, dpastor commented
Just re-requesting review for the latest 2 commits:
https://github.com/Telefonica/mistica-android/pull/91/commits/da2532b3baa82194d63d935ea8420431df7b55ba -> Fixes from detailed review with @yceballost. Just details found after checking component behaviour. Also makes actions/subtitle optional, which were incorrectly mandatory.
https://github.com/Telefonica/mistica-android/pull/91/commits/fe062aa88083b7efa33976a3584f839a1ad11bc9 -> Documentation

2021-07-07 12:11 UTC, manolovn approved these changes
nice! thx!

2021-07-07 13:07 UTC, mbarrben approved these changes

2021-07-08 07:25 UTC, merged