ANDROID-9827 add max lines attr to title, subtitle and description in…
Telefonica/mistica-android pull request #97
Opened 2021-09-01 12:39 UTC by manolovn

### :goal_net: What's the goal?
Add max lines attr to title, subtitle and description in listRowView component

### :construction: How do we do it?
Three new attributes to support max lines in title, subtitle and description in `ListRowView` component are added. The attributes are `listRowTitleMaxLines`, `listRowSubtitleMaxLines` and `listRowDescriptionMaxLines`.
The catalog is updated to show how is the impact in the current behavior.
This is not a breaking change neither a bugfix, so the new version should be 2.5.0

### ☑️ Checks
- [ ] I updated the documentation (readmes, wikis, etc). If no need to update documentation explain why.
- [x] Tested with dark mode.
- [x] Tested with API 21.

### :test_tube: How can I test this?
_If it cannot be tested explain why._
- [x] 🖼️ Screenshots/Videos
![image](https://user-images.githubusercontent.com/944814/131672515-55737da4-776f-46b1-b780-c07a6458f127.png)
![image](https://user-images.githubusercontent.com/944814/131672570-0d26ac4e-7141-4fd0-b9e3-62512f0a76c2.png)

- [ ] Reviewed by Mistica design team

2021-09-02 15:25 UTC, dpastor requested changes
@yceballost we agreed on february that we were not forcing to any max lines in mistica components due accesibility.
Check -> https://jira.tid.es/browse/ANDROID-8906
Has anything changed?

2021-09-02 16:23 UTC, yceballost commented
> Although in this case we are allowing configuring max lines for the component (Not forcing any as we agreed on february) ->
> 
> [jira.tid.es/browse/ANDROID-8906](https://jira.tid.es/browse/ANDROID-8906)
> 
> Reason was mainly accessibility. I'm not sure if setting a max lines configuration would be the correct way of handling these bugs, because of the same reason of we removed this configuration.
> 
> WDYT @yceballost

Yeah, at the beginning of the lists specs, we limited text lines but after a while, we removed the limitation. In web component exists the possibility to limit or not the texts lines. I think it is better to keep both alternatives (being the not limited one set up by default)

An example of each case in web component

https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AlCB3AOgOwAS4EtJsBeYHffJAYQICcwAbGXAIwEMwBrAczogCu2KNQiMIdMpHF0AzgDpsMAQBc67RgBkMAX1yyCALxhkALAAYdAPgqUqASWIBlABYQADihg8BjdnVwAehs8SiRA2gZmEPwdWyIIbCcjE2ALONCVAhVmEkwQABVs5lwANxg6AE9ccWweGsT62vqsnJZ0bJcGuu6W4ph821hZMDoCdyzEvJAAERgRsYmCRLKK6ubezdaSjpUujY3tgZBbRIAFOnnZMgAKAEpcEitcYB0M4JxUDHjiMlsqSJMFgcbh8QTCUQyKRiCQKJSqdRaXT6FJmSwxOy4JCORKuDxeHx%2BAIfUJUCL0IEYjL4BJJVFpSy2I6aAhKWQAWXYAA9pgBGQaZfrTIptVZVTYHRq4I64Xb7KWHfoC-DDUbjSakfJzBbq5Z4criyU9RWiuUSqVHZW4VWLDUstmcnn5fknULnS6ya7Ae6PZ6vd4hEAAGhAexgAFt5ggANogdkQUoEWQqfwgAC6IY6UD2shjAGYAGzmNM6IA

2021-09-03 06:39 UTC, jeslat approved these changes

2021-09-03 07:07 UTC, dpastor commented
> > Although in this case we are allowing configuring max lines for the component (Not forcing any as we agreed on february) ->
> > [jira.tid.es/browse/ANDROID-8906](https://jira.tid.es/browse/ANDROID-8906)
> > Reason was mainly accessibility. I'm not sure if setting a max lines configuration would be the correct way of handling these bugs, because of the same reason of we removed this configuration.
> > WDYT @yceballost
> 
> Yeah, at the beginning of the lists specs, we limited text lines but after a while, we removed the limitation. In web component exists the possibility to limit or not the texts lines. I think it is better to keep both alternatives (being the not limited one set up by default)
> 
> I think is better to keep "feature parity" between platforms Mística component.
> 
> An example of each case in web component
> 
> https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AlCB3AOgOwAS4EtJsBeYHffJAYQICcwAbGXAIwEMwBrAczogCu2KNQiMIdMpHF0AzgDpsMAQBc67RgBkMAX1yyCALxhkALAAYdAPgqUqASWIBlABYQADihg8BjdnVwAehs8SiRA2gZmEPwdWyIIbCcjE2ALONCVAhVmEkwQABVs5lwANxg6AE9ccWweGsT62vqsnJZ0bJcGuu6W4ph821hZMDoCdyzEvJAAERgRsYmCRLKK6ubezdaSjpUujY3tgZBbRIAFOnnZMgAKAEpcEitcYB0M4JxUDHjiMlsqSJMFgcbh8QTCUQyKRiCQKJSqdRaXT6FJmSwxOy4JCORKuDxeHx%2BAIfUJUCL0IEYjL4BJJVFpSy2I6aAhKWQAWXYAA9pgBGQaZfrTIptVZVTYHRq4I64Xb7KWHfoC-DDUbjSakfJzBbq5Z4criyU9RWiuUSqVHZW4VWLDUstmcnn5fknULnS6ya7Ae6PZ6vd4hEAAGhAexgAFt5ggANogdkQUoEWQqfwgAC6IY6UD2shjAGYAGzmNM6IA

Makes sense then. Thanks a lot @yceballost !

2021-09-03 07:09 UTC, yceballost approved these changes
lgtm! ✨

2021-09-03 07:16 UTC, dpastor approved these changes

2021-09-03 07:59 UTC, AnaMontes11 commented
All good for me as well!

2021-09-03 08:02 UTC, AnaMontes11 approved these changes
All good for me as well!

2021-09-03 10:38 UTC, manolovn commented
Thx you all!

2021-09-03 12:04 UTC, merged